### ISSUE TITLE
Turn on discussions for this repo?

### ISSUE THREAD

**Issue by bmann** [bluesky-social/atproto-ecosystem#14]
From a discussion with @myConsciousness 

https://staging.bsky.app/profile/shinyakato.dev/post/3jtif2kbx232g

@arcalinea do you want to start by hosting discussion for 3rd party devs here?

could we get Github discussions turned on for this repo? Or in the [atproto](https://github.com/bluesky-social/atproto) repo?

happy to also “do nothing” — we know you have a lot going on ;)

**Comment by myConsciousness** [comment]
Hi @bmann , 

Thanks for creating this discussion! 

I feel many developers seem to be unaware discussion tab of this repository in the first place or don't know how to use it. 

If this place is to be a Forum for developers, there should be a guide in the README :)

**Comment by myConsciousness** [comment]
@bmann 

Thanks for this issue, I wish the best of luck in finding a better solution :)

**Comment by bnewbold** [comment]
Reminder that we do have a matrix channel for developer discussion: `#bluesky-dev:matrix.org`

We have not always been the most active on it, but that does exist today, and devs have been helping each other and we do check in and answer questions there.

**Comment by bmann** [comment]
Yep totally aware of Matrix but doesn’t help with asynch discussions and lots of answering the same questions. 

Had a good back and forth with @bnewbold and here’s the answer right now https://staging.bsky.app/profile/bnewbold.net/post/3jtk5zqswyc2y

**Comment by emilyliu7321** [comment]
we'll be deprecating this repo shortly and using https://atproto.com/community/projects as the public-facing page for community projects. you can also make PRs to that site here: https://github.com/bluesky-social/atproto-website

i'm going to close this issue in favor of using the matrix channel, in-app discussion, or the community dev discord for now, with hopefully a longer-lasting and more easily searchable option/forum to come
