### ISSUE TITLE
Another database of community projects

### ISSUE THREAD

**Issue by dgellow** [bluesky-social/atproto-ecosystem#42]
Hi there,

Just to let you know, I maintain a list of projects made by the ATP/Bluesky community at https://ecosystem.elborai.software. I started based on this repository, added everything that was in PRs. And other projects I did learn about.

**Comment by ianklatzco** [comment]
cool!

one thing i've been meaning to do is add this list of bots somewhere:

https://scrapbox.io/Bluesky/Bot

i think it would be cool to make a bsky account where all the posts are pointers to / short descriptions of / screenshots of the bots.

**Comment by dgellow** [comment]
Oh yeah, that's a good idea Ian. For now I will add bots to my database, there is so many of them it kind of make sense to add a new category. Thanks for your link, it's very useful to see projects from the Japanese cluster, I find it difficult to discover things cross-languages.

**Comment by emilyliu7321** [comment]
thanks for this list! 

we'll be deprecating this repo shortly and using https://atproto.com/community/projects as the public-facing page for community projects. you can also make PRs to that site here: https://github.com/bluesky-social/atproto-website -- feel free to add anything from your list!
