### ISSUE TITLE
Please add https://github.com/davidcarryer/pBsky to the ecosystem.

### ISSUE THREAD

**Issue by davidcarryer** [bluesky-social/atproto-ecosystem#52]
Fun little example using atprototools to create a linux command line client.  Thanks.

**Comment by ianklatzco** [comment]
https://github.com/davidcarryer/pBsky
![image](https://user-images.githubusercontent.com/1487413/236845145-53e52a27-bb7a-45cd-b33c-d2fb69967651.png)

**Comment by emilyliu7321** [comment]
added in #55 👍
